# Generated by Django 3.2.9 on 2023-04-14 02:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_auto_20230414_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='like_users',
            field=models.ManyToManyField(related_name='like_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
