# Generated by Django 3.2.18 on 2023-03-24 03:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Comedy', 'Comedy'), ('horror', 'horror'), ('Romance', 'Romance')], max_length=30),
        ),
        migrations.AlterField(
            model_name='movie',
            name='score',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(5, '0~5 사이 평점'), django.core.validators.MinValueValidator(0, '0~5 사이 평점')]),
        ),
    ]
